# "partial" or "full" - whether to use a full laser scan or only a narrow section in front of the robot
string scan_mode
---
# container corners - result of detection process
geometry_msgs/Point[] corners
---
# feedback message
float32 percent_complete
