# container corners as input - used to compute relative position of charging station
geometry_msgs/Point[] corners
---
# result - pose in front of the charging station
geometry_msgs/PoseStamped station_pos
---
# feedback
float32 percent_complete
